sudo: required
dist: trusty
addons:
  chrome: stable
language: java
jdk: openjdk8
services: mysql
install: true
  - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/
- export CHROME_BIN=chromium-browser
script:
- mvn install
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y