language: java
jdk: openjdk8
services: mysql
install: true
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser
script:
- mvn install
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y