os: linux
sudo: required
dist: xenial
addons:
  chrome: stable
language: java
jdk: openjdk8
before-install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
services: mysql
install: true
- wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
- export CHROME_BIN=chromium-browser
before_script:
-sudo ls
- mysql -e 'CREATE DATABASE alumnos;'
- mysql -e 'CREATE TABLE alumnos.alumno (idAlumno int(11) NOT NULL, nombre varchar(45) DEFAULT NULL, edad int(11) DEFAULT NULL, calificacion int(11) DEFAULT NULL, email varchar(45) DEFAULT NULL, PRIMARY KEY (idAlumno));'
script:
- mvn install
- whereis google-chrome-stable
- whereis chromedriver
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y